fix: undefined reference to `Connection::instancePtr`, undefined handleMqttMessage()
- Introduces a static instance pointer for the Connection singleton pattern
- Implement forward declaration to `handleMqttMessage()`